create database customer_behaviour;
use customer_behaviour;

select *from customer_shopping_behavior;

-- what is the total revenue generated by male v/s female customers
 select gender, sum(purchase_amount) as total_revenue
 from customer_shopping_behavior
 group by gender;
 
 
 -- Which customer used a discount but still spent more than the 
--  average purchase amount

select customer_id, purchase_amount
from customer_shopping_behavior
where discount_applied='Yes' 
and purchase_amount>=
(select avg(purchase_amount) from customer_shopping_behavior);

-- which are the top 5 products with the highest average review rating
select item_purchased, avg(review_rating) as 'average_product_review'
from customer_shopping_behavior
group by item_purchased
order by average_product_review desc
limit 5;

-- compare the average purchased amount between standard and express shipping
select shipping_type, round(avg(purchase_amount),2) as average_purchase_amt
from customer_shopping_behavior
where shipping_type in ('Express', 'Standard')
group by shipping_type;


-- Do subscribed customers spend more? Compare avergae spend and total revenue
-- between subscribers and non-subscribers
select subscription_status, count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_purchase_amt,
round(sum(purchase_amount),2) as total_revenue
from customer_shopping_behavior
group by subscription_status
order by total_revenue desc;

-- Which 5 products have the highest percentage of purchases 
-- with discount applied
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2)
as discount_rating
from customer_shopping_behavior
group by item_purchased
order by discount_rating desc
limit 5;


-- Segment customers into New, Returning and Loyal based on previous purchases.
with customer_type as
(
select customer_id, previous_purchases,
case 
	when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer_shopping_behavior
)

select customer_segment, count(*)
from customer_type
group by customer_segment;


-- what are the top 3 most purchased products within each category
with item_count as 
(
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) rn
from customer_shopping_behavior
group by category, item_purchased
)
select *from item_count
where rn<=3;

-- Are customers who are repeat buyers (more than 5 previous purchase) also
-- likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases>5
group by subscription_status;

-- what is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer_shopping_behavior
group by age_group 
order by total_revenue desc;



 